version: '3'

services:
  redis:
    image: 'redis'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - '6379:6379'
    volumes:
    - ./redis/data:/usr/local/etc/redis/data

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
    - redis:redis
    ports:
    - "8081:8081"

  api:
    build: ./api/
    ports:
    - "3000:3000"
    command: npm run start
    volumes:
    - ./api/:/usr/src/app
    - /usr/src/app/node_modules
    links:
    - redis

  app:
    build: ./app/
    ports:
    - "8080:8080"
    command: npm run serve
    volumes:
    - ./app/:/usr/src/app
    - /usr/src/app/node_modules