version: '3'

services:
  redis:
    image: 'redis'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - '6379:6379'
    volumes:
    - ./redis/data:/usr/local/etc/redis/data

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
    - redis:redis
    ports:
    - "8081:8081"
